#DOCKER VERSION
version: "3.9"
#Services
services:
  mysql:
    platform: linux/x86_64
    #image: mysql:latest
    image: mysql:5.7
    ports:
      # - "3306:3332 Out port example"
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
      #docker hub
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest    
    environment:
      PMA_HOST: mysql
      #PMA_USER: root
      #PMA_PASSWORD: "12345678"
    depends_on:
      - mysql
    ports:
      - "8080:80"